{% set name = "graphql-server-core" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa810f811cd91dd938ac49819562c3a12f2b6bf141164f984b16359359133983

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - graphql-core >=2.1
    - promise

test:
  imports:
    - graphql_server

about:
  home: https://graphene-python.org/
  license: MIT
  license_family: MIT
  # requested inclusion of license file in distro https://github.com/graphql-python/graphql-server-core/pull/14
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'This is the core package for using GraphQL in a custom server easily.'
  doc_url: https://docs.graphene-python.org/en/latest/
  dev_url: https://github.com/graphql-python/graphql-server-core

extra:
  recipe-maintainers:
    - carlodri
    - dhirschfeld
