travis:
  secure:
    BINSTAR_TOKEN: vs5SQ582jrKdsCgyaNtyzLP5UJUFTfB3PV7ESPrm2H2mXQXUNGCooV4U/HhjXtW4hTGvtHOOe68DGoD7YfL5nmownqcgxT/M7XGGPNfSMhMq2finz9O4hALi7BheXy6mxd4EUVavCBbmcrqIlfg7P5uXyYTetY07ILoFFDKU5cSJ5fLxdxAhLAQcqkvb5KCvuP3TYzhLok9IlTY7+ITp4NK9m1d2X+OB6YT14keum9riNFVlQ5/bFQQxp2zq/X8D7sPU9fW0xJXQ737czhEvGQDVNOrQ+d5y2uKvofJkqgcLZjvZmLcB34oIWwSTyK2FMEK0OnOrrP0vcRFpokjrCp859HBp61C9UCQsVk6ieZ+ufzLHC+Ns1E08FafLNFUceAWLotzVFi4BOg4JO0ZNRTbxaNPI28+fn+C1HjwYXEx0uJd7T8aCfHVLApMD9nGc/ATSBmIdTiyJWKpGt9CDw0F/g7xDoo4yLWLElNduP8ba0kWZPlLSmtRPBz4PhVPL1HH+yEcLJMkl51vZuhrAFRp8E8oaW6Ydql28yhFPRRwJPHkS2VwqoIoM6euWTWxD2vH0uOf6WT1VmoKOpWt7ZbU2lt2WhcHDMTvWrN9wAVWPWmAwneGxhxmxofGuA8pEBguX+kB4K134gIEp1QJZQM37bSPY3QHEte7yjqE3FDs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
